import {
  LayoutDashboard,
  Truck,
  Users,
  Route,
  Wrench,
  FileText,
  BarChart3,
  Bell,
  Settings,
  Navigation,
  Fuel,
  FolderOpen,
  AlertTriangle,
  ShieldCheck,
  ClipboardList,
  GraduationCap,
  Shield,
  DollarSign,
  TrendingUp,
  Receipt,
  PieChart,
  Package,
  Warehouse,
  Inbox,
  FileCheck,
  UserCheck,
  Clipboard,
  Download,
  Wallet,
  TrendingDown,
  IndianRupee,
} from "lucide-react";

export const roleConfigs = {
  operations: {
    title: "Mission Control",
    subtitle: "Operations Lead",
    color: "bg-[#1E3A5F]",
    items: [
      { label: "Dashboard", path: "/dashboard/operations", icon: LayoutDashboard },
      { label: "Fleet", path: "/dashboard/operations/fleet", icon: Truck },
      { label: "Vehicles", path: "/dashboard/operations/vehicles", icon: Truck },
      { label: "Drivers", path: "/dashboard/operations/drivers", icon: Users },
      { label: "Trips", path: "/dashboard/operations/trips", icon: Route },
      { label: "Assignments", path: "/dashboard/operations/assignments", icon: ClipboardList },
      { label: "Maintenance", path: "/dashboard/operations/maintenance", icon: Wrench },
      { label: "Reports", path: "/dashboard/operations/reports", icon: FileText },
      { label: "Fleet Analytics", path: "/dashboard/operations/reports/fleet", icon: Truck },
      { label: "Fuel Analytics", path: "/dashboard/operations/reports/fuel", icon: Fuel },
      { label: "Revenue", path: "/dashboard/operations/reports/revenue", icon: IndianRupee },
      { label: "Vehicle ROI", path: "/dashboard/operations/reports/roi", icon: TrendingUp },
      { label: "Cost", path: "/dashboard/operations/reports/operational-cost", icon: Wallet },
      { label: "Export", path: "/dashboard/operations/reports/export", icon: Download },
      { label: "Analytics", path: "/dashboard/operations/analytics", icon: BarChart3 },
      { label: "Notifications", path: "/dashboard/operations/notifications", icon: Bell },
      { label: "Settings", path: "/dashboard/operations/settings", icon: Settings },
    ],
  },
  "road-captain": {
    title: "Driver Cockpit",
    subtitle: "Road Captain",
    color: "bg-[#059669]",
    items: [
      { label: "Dashboard", path: "/dashboard/road-captain", icon: LayoutDashboard },
      { label: "My Trips", path: "/dashboard/road-captain/my-trips", icon: Route },
      { label: "Trip History", path: "/dashboard/road-captain/trip-history", icon: FileText },
      { label: "Assigned Vehicle", path: "/dashboard/road-captain/assigned-vehicle", icon: Truck },
      { label: "Navigation", path: "/dashboard/road-captain/navigation", icon: Navigation },
      { label: "Fuel Logs", path: "/dashboard/road-captain/fuel-logs", icon: Fuel },
      { label: "Documents", path: "/dashboard/road-captain/documents", icon: FolderOpen },
      { label: "Emergency", path: "/dashboard/road-captain/emergency", icon: AlertTriangle },
      { label: "Profile", path: "/dashboard/road-captain/profile", icon: UserCheck },
      { label: "Settings", path: "/dashboard/road-captain/settings", icon: Settings },
    ],
  },
  safety: {
    title: "Safety Command",
    subtitle: "Safety Officer",
    color: "bg-[#D97706]",
    items: [
      { label: "Dashboard", path: "/dashboard/safety", icon: LayoutDashboard },
      { label: "Drivers", path: "/dashboard/safety/drivers", icon: Users },
      { label: "Compliance", path: "/dashboard/safety/compliance", icon: ShieldCheck },
      { label: "Licenses", path: "/dashboard/safety/licenses", icon: ClipboardList },
      { label: "Incidents", path: "/dashboard/safety/incidents", icon: AlertTriangle },
      { label: "Training", path: "/dashboard/safety/training", icon: GraduationCap },
      { label: "Inspections", path: "/dashboard/safety/inspections", icon: Shield },
      { label: "Reports", path: "/dashboard/safety/reports", icon: FileText },
      { label: "Settings", path: "/dashboard/safety/settings", icon: Settings },
    ],
  },
  finance: {
    title: "Finance Command",
    subtitle: "Finance Hub",
    color: "bg-[#7C3AED]",
    items: [
      { label: "Dashboard", path: "/dashboard/finance", icon: LayoutDashboard },
      { label: "Expenses", path: "/dashboard/finance/expenses", icon: DollarSign },
      { label: "Fuel Cost", path: "/dashboard/finance/fuel-cost", icon: Fuel },
      { label: "Maintenance Cost", path: "/dashboard/finance/maintenance-cost", icon: Wrench },
      { label: "Revenue", path: "/dashboard/finance/revenue", icon: TrendingUp },
      { label: "ROI", path: "/dashboard/finance/roi", icon: PieChart },
      { label: "Invoices", path: "/dashboard/finance/invoices", icon: Receipt },
      { label: "Reports", path: "/dashboard/finance/reports", icon: FileText },
      { label: "Analytics", path: "/dashboard/finance/analytics", icon: BarChart3 },
      { label: "Settings", path: "/dashboard/finance/settings", icon: Settings },
    ],
  },
  destination: {
    title: "Arrival Hub",
    subtitle: "Destination Control",
    color: "bg-[#BE123C]",
    items: [
      { label: "Dashboard", path: "/dashboard/destination", icon: LayoutDashboard },
      { label: "Incoming", path: "/dashboard/destination/incoming", icon: Inbox },
      { label: "Completed", path: "/dashboard/destination/completed", icon: FileCheck },
      { label: "Warehouse", path: "/dashboard/destination/warehouse", icon: Warehouse },
      { label: "Inventory", path: "/dashboard/destination/inventory", icon: Package },
      { label: "Receivers", path: "/dashboard/destination/receivers", icon: Users },
      { label: "Proof of Delivery", path: "/dashboard/destination/proof-of-delivery", icon: Clipboard },
      { label: "Reports", path: "/dashboard/destination/reports", icon: FileText },
      { label: "Settings", path: "/dashboard/destination/settings", icon: Settings },
    ],
  },
};
