const MAINTENANCE_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
};

const MAINTENANCE_STATUS_ARRAY = Object.values(MAINTENANCE_STATUS);

module.exports = { MAINTENANCE_STATUS, MAINTENANCE_STATUS_ARRAY };
