const ROLES = {
  OPERATION_LEAD: 'OPERATION_LEAD',
  ROAD_CAPTAIN: 'ROAD_CAPTAIN',
  SAFETY_OFFICER: 'SAFETY_OFFICER',
  FINANCE_HUB: 'FINANCE_HUB',
  DESTINATION_CONTROL: 'DESTINATION_CONTROL',
};

const ROLES_ARRAY = Object.values(ROLES);

module.exports = { ROLES, ROLES_ARRAY };
